// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfvukmfhwonsfptmcabf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmdnVrbWZod29uc2ZwdG1jYWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNzkxMTUsImV4cCI6MjA1Nzg1NTExNX0.4B_TEeOEFm1SBGWBN7kWCKD8jP6aLP_vLW0KeReMfms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);